name: CONTEMPORARYDANCE
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7322956551797688
title: COMPANY DANZANTE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fafafa'
    - '#724a57'
    - '#4e7b9c'
    - '#aaa1b1'
  brandStrength: 0.0713616122957319
  lightness: 0.984513605479151
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
