name: CONTEMPORARYDANCE
favicon: null
layout_spectrum: 0.12859078054316342
typography_spectrum: 0.7322956551797688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0713616122957319
  lightness: 0.984513605479151
  saturation: 0.013684597797691822
  rhythmicContrast: 0.10069040395319462
purpose: []
